---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install ipa-server
  yum:
    name: ipa-server
    state: present
  tags: ipa-server install 

- name: install ipa-server dns 
  yum:
    name: ipa-server-dns
    state: present
  tags: ipa-server-dns install

- name: install parametrs
  shell: > 
    ipa-server-install
    --hostname=rc.otus.local
    --domain=otus.local
    --realm=OTUS.LOCAL
#    --ds-password "{{ ds-password }}"
#    --admin-password "{{ admin-password }}"
#    --forwarder "{{ forwarder }}"
#    --mkhomedir
#    --setup-dns
#    --auto-reverse
#    --unattended
  tags: install parametrs
