---
- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install ipa-server
  yum:
    name: ipa-server
    state: present
  tags: ipa-server install 

- name: install ipa-server dns 
  yum:
    name: ipa-server-dns
    state: present
  tags: ipa-server-dns install

- name: install ipa-server dns
  yum:
    name: "{{ packages }}"
    state: present
  tags: packages install

- name: set timezone # Задаём часовой пояс.
  timezone:
    name: "{{ ntp_timezone }}"
  notify:
    - restart ntpd

- name: hostname # Зададим машине нужное имя.
  hostname: 
    name: "{{ hostname }}.{{ domain }}"

- name: hosts # Подправим Hosts: заменим 127.0.0.1 на реальный адрес с соотнесём его с fqdn
  replace:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1(\s+){{ hostname }}(\s+){{ hostname }}.*'
    replace: "{{ my_ip }} {{ hostname }}.{{ domain }} {{ hostname }}"
    backup: yes # Бекап!


- name: install parametrs
  shell: "ipa-server-install -U --ds-password={{ dspassword }} --admin-password={{ adminpassword }} --domain={{ domain }} --realm={{ realm }} --hostname={{ hostname }}.{{ domain }} --setup-dns --forwarder {{ forwarder }} --auto-reverse --unattended" 
  tags: install parametrs
