---
# tasks file for client

- name: install epel-release
  yum:
    name: epel-release
    state: present
- name: install ipa-client
  yum:
    name: ipa-client
    state: present
  notify:
    - restart ipa-client
    - enabled ipa-client
  tags: ipa-client install

