---
# handlers file for nginx-role

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
- name: enabled nginx
  systemd:
    name: nginx
    enabled: yes

...
